apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      initContainers:
        - name: wait-for-dependencies
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z servicediscovery 8761 && nc -z configserver 8888; do echo waiting for dependencies; sleep 2; done;']
      containers:
        - name: api-gateway
          image: micorservices-api-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: spring-config
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30090
