apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      initContainers:
        - name: wait-for-dependencies
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z servicediscovery 8761 && nc -z configserver 8888 && nc -z mysqldb 3306; do echo waiting for dependencies; sleep 2; done;']
      containers:
        - name: product-service
          image: micorservices-product-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: spring-config
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: NodePort
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
